import { StyleSheet } from 'react-native';
import { moderateScale as RFValue } from 'react-native-size-matters';
import Colors from '../../config/colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingHorizontal: RFValue(20),
    paddingVertical: RFValue(25),
  },
  header: {
    marginBottom: RFValue(30),
  },
  headerTitle: {
    fontSize: RFValue(24),
    fontWeight: 'bold',
    color: Colors.textPrimary,
    marginBottom: RFValue(8),
  },
  headerSubtitle: {
    fontSize: RFValue(14),
    color: Colors.textSecondary,
    lineHeight: RFValue(20),
  },
  adminLoginButton: {
    alignSelf: 'flex-start',
    marginTop: RFValue(12),
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: RFValue(20),
    paddingHorizontal: RFValue(12),
    paddingVertical: RFValue(6),
    backgroundColor: Colors.backgroundAlt,
  },
  adminLoginButtonText: {
    fontSize: RFValue(12),
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  adminStatusRow: {
    marginTop: RFValue(12),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: RFValue(10),
  },
  adminStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EAF9F0',
    borderColor: '#A5E2BC',
    borderWidth: 1,
    borderRadius: RFValue(16),
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(6),
  },
  adminStatusDot: {
    width: RFValue(8),
    height: RFValue(8),
    borderRadius: RFValue(4),
    backgroundColor: '#1D9B52',
    marginRight: RFValue(6),
  },
  adminStatusText: {
    fontSize: RFValue(12),
    fontWeight: '700',
    color: '#1C6F3F',
  },
  simpleUserButton: {
    borderRadius: RFValue(16),
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.backgroundAlt,
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(6),
  },
  simpleUserButtonText: {
    fontSize: RFValue(11),
    fontWeight: '700',
    color: Colors.textSecondary,
  },
  selectedAmountContainer: {
    backgroundColor: Colors.primaryLight,
    borderRadius: RFValue(12),
    padding: RFValue(16),
    marginBottom: RFValue(30),
    alignItems: 'center',
    borderColor: Colors.primary,
    borderWidth: 2,
  },
  selectedAmountLabel: {
    fontSize: RFValue(12),
    color: Colors.textSecondary,
    marginBottom: RFValue(4),
  },
  selectedAmount: {
    fontSize: RFValue(32),
    fontWeight: 'bold',
    color: Colors.primary,
  },
  presetsContainer: {
    marginBottom: RFValue(30),
  },
  sectionTitle: {
    fontSize: RFValue(16),
    fontWeight: '600',
    color: Colors.textPrimary,
    marginBottom: RFValue(12),
  },
  presetsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: RFValue(12),
  },
  presetButton: {
    flex: 1,
    paddingVertical: RFValue(16),
    paddingHorizontal: RFValue(12),
    borderRadius: RFValue(10),
    backgroundColor: Colors.backgroundAlt,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetButtonActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  presetButtonText: {
    fontSize: RFValue(18),
    fontWeight: 'bold',
    color: Colors.textPrimary,
  },
  presetButtonTextActive: {
    color: Colors.white,
  },
  loadingPresetsContainer: {
    paddingVertical: RFValue(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingPresetsText: {
    marginTop: RFValue(6),
    fontSize: RFValue(13),
    color: Colors.textSecondary,
  },
  firebaseErrorContainer: {
    marginBottom: RFValue(10),
    backgroundColor: '#FFF3E0',
    borderWidth: 1,
    borderColor: '#FFCC80',
    borderRadius: RFValue(8),
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(8),
  },
  firebaseErrorText: {
    fontSize: RFValue(12),
    color: '#8A4B00',
    marginBottom: RFValue(6),
    lineHeight: RFValue(17),
  },
  retryFirebaseButton: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.primary,
    borderRadius: RFValue(6),
    paddingHorizontal: RFValue(10),
    paddingVertical: RFValue(6),
  },
  retryFirebaseButtonText: {
    fontSize: RFValue(12),
    fontWeight: '700',
    color: Colors.white,
  },
  adminPanelContainer: {
    marginBottom: RFValue(24),
    backgroundColor: Colors.backgroundAlt,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: RFValue(12),
    padding: RFValue(14),
  },
  adminPanelHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: RFValue(10),
  },
  adminPanelTitle: {
    fontSize: RFValue(15),
    fontWeight: '700',
    color: Colors.textPrimary,
  },
  adminPanelSubtitle: {
    fontSize: RFValue(12),
    color: Colors.textSecondary,
    marginTop: RFValue(3),
  },
  adminEditButton: {
    paddingVertical: RFValue(8),
    paddingHorizontal: RFValue(12),
    borderRadius: RFValue(8),
    borderWidth: 1,
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryLight,
  },
  adminEditButtonText: {
    fontSize: RFValue(12),
    fontWeight: '600',
    color: Colors.primary,
  },
  adminEditorContainer: {
    marginTop: RFValue(14),
    gap: RFValue(10),
  },
  adminEditorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: RFValue(10),
  },
  adminEditorLabel: {
    fontSize: RFValue(14),
    color: Colors.textPrimary,
    fontWeight: '600',
  },
  adminEditorInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: RFValue(8),
    paddingHorizontal: RFValue(10),
    backgroundColor: Colors.white,
    minWidth: RFValue(95),
  },
  adminEditorCurrencySymbol: {
    fontSize: RFValue(15),
    color: Colors.textPrimary,
    fontWeight: '700',
    marginRight: RFValue(4),
  },
  adminEditorInput: {
    flex: 1,
    paddingVertical: RFValue(8),
    fontSize: RFValue(14),
    color: Colors.textPrimary,
    minWidth: RFValue(45),
  },
  adminSaveButton: {
    marginTop: RFValue(4),
    backgroundColor: Colors.primary,
    borderRadius: RFValue(8),
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: RFValue(11),
  },
  adminSaveButtonDisabled: {
    opacity: 0.7,
  },
  adminSaveButtonText: {
    fontSize: RFValue(14),
    fontWeight: '700',
    color: Colors.white,
  },
  customAmountContainer: {
    marginBottom: RFValue(30),
  },
  customInputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.backgroundAlt,
    borderRadius: RFValue(10),
    borderWidth: 2,
    borderColor: Colors.border,
    paddingHorizontal: RFValue(12),
    marginBottom: RFValue(12),
  },
  currencySymbol: {
    fontSize: RFValue(20),
    fontWeight: 'bold',
    color: Colors.textPrimary,
    marginRight: RFValue(4),
  },
  customInput: {
    flex: 1,
    paddingVertical: RFValue(12),
    fontSize: RFValue(16),
    color: Colors.textPrimary,
  },
  customAmountButton: {
    paddingVertical: RFValue(12),
    paddingHorizontal: RFValue(16),
    backgroundColor: Colors.primaryLight,
    borderRadius: RFValue(8),
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  customAmountButtonText: {
    fontSize: RFValue(14),
    fontWeight: '600',
    color: Colors.primary,
  },
  continueButton: {
    paddingVertical: RFValue(14),
    paddingHorizontal: RFValue(20),
    backgroundColor: Colors.primary,
    borderRadius: RFValue(10),
    alignItems: 'center',
    marginTop: RFValue(10),
    marginBottom: RFValue(20),
  },
  continueButtonDisabled: {
    backgroundColor: Colors.gray400,
  },
  continueButtonText: {
    fontSize: RFValue(16),
    fontWeight: '600',
    color: Colors.white,
  },
});

export default styles;
